---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels: {{- include "core-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: api
...
